server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rjxy(SB307)wuzongbo
    url: jdbc:mysql://47.106.220.247:3306/mymall?useUnicode=true&characterEncoding=utf8

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml